---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
 
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  deprecations_as_errors: true
  client_rb:
    ssl_verify_mode: :verify_none
    verify_api_cert: false

verifier:
  name: inspec
 
platforms:
  - name: Windows2012R2
    driver_config:
      box: mwrock/Windows2012R2
      gui: false
    transport:
      name: winrm
      elevated: true
  - name: CentOS67
    driver_config:
      box: bento/centos-6.7
      gui: false

suites:
  - name: default
    run_list:
      - recipe[cbprotect_agent::default]
    verifier:
      inspec_tests:
      - test/smoke/default
      attributes:
  - name: remove
    run_list:
      - recipe[cbprotect_agent::default]
      - recipe[cbprotect_agent::remove]
